// Downloads the exact Inter files Google Fonts serves for the design's
// `family=Inter:wght@400..800` request and writes a self-hosted @font-face
// sheet that keeps the family name "Inter" (the design references it inline).
// Only the latin + latin-ext subsets are kept (es/ca/en). Run: pnpm fonts
import { mkdir, writeFile } from "node:fs/promises";

const CSS_URL = "https://fonts.googleapis.com/css2?family=Inter:wght@400..800&display=swap";
const UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0 Safari/537.36";
const KEEP = ["latin-ext", "latin"];

const css = await (await fetch(CSS_URL, { headers: { "user-agent": UA } })).text();
const blocks = [...css.matchAll(/\/\* ([a-z-]+) \*\/\s*(@font-face\s*{[^}]+})/g)];
await mkdir("public/fonts", { recursive: true });

let out = "/* Generated by scripts/fetch-fonts.mjs from Google Fonts. Do not edit. */\n";
for (const [, subset, block] of blocks) {
  if (!KEEP.includes(subset)) continue;
  const url = block.match(/url\((https:[^)]+)\)/)[1];
  const file = `inter-${subset}.woff2`;
  const buf = Buffer.from(await (await fetch(url)).arrayBuffer());
  await writeFile(`public/fonts/${file}`, buf);
  out += `/* ${subset} */\n${block.replace(url, `/fonts/${file}`)}\n`;
  console.log(`${file}  ${buf.length} bytes`);
}
await writeFile("src/styles/fonts.css", out);
