// Generates src/components/icon/paths.ts from design/kf-icons.js so the icon
// SVG markup stays byte-identical to the design. Run: pnpm gen:icons
import { readFile, writeFile, mkdir } from "node:fs/promises";
import vm from "node:vm";

const src = await readFile("design/kf-icons.js", "utf8");
const body = src.slice(src.indexOf("const P="), src.indexOf("class KfI"));
const P = vm.runInNewContext(`${body}; P`, {});
const names = Object.keys(P);

let out = "// Generated by scripts/gen-icons.mjs from design/kf-icons.js. Do not edit.\n\n";
out += `export const ICON_PATHS = {\n${names.map((n) => `  ${n}: ${JSON.stringify(P[n])},`).join("\n")}\n} as const;\n\n`;
out += "export type IconName = keyof typeof ICON_PATHS;\n";
await mkdir("src/components/icon", { recursive: true });
await writeFile("src/components/icon/paths.ts", out);
console.log(`${names.length} icons`);
